name = "hex-hensel"
defaultTargets = ["HexHensel"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "0e0fd9b6e0afdcda5d78dcbceb262b900634f65e"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "a3d2bc38d47673cc724feb01ba277e787b313719"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a3ab4fd9a79efbe6b07337836b3b5828d22d65a6"

[[lean_lib]]
name = "HexHensel"
precompileModules = true
