name = "hex-hensel"
defaultTargets = ["HexHensel"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "3d2cc1c30b0e17dfec35858e9d5fa8d75e1f241b"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "0166cc099045e0366efd6a152f633c9e9baf0550"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "591c146eeee0ef301a110cd33c19cc0cf1e07352"

[[lean_lib]]
name = "HexHensel"
precompileModules = true
