name = "hex-hensel"
defaultTargets = ["HexHensel"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "63d11e9652020e83629808977bff618e99d21234"

[[require]]
name = "HexPolyZ"
git = "https://github.com/leanprover/hex-poly-z.git"
rev = "7d7fdebb1bde00648a951177e3042a3ffbb2a8ea"

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "365881fb205210e8d27c5eb011f7ddb3fe020373"

[[lean_lib]]
name = "HexHensel"
precompileModules = true
